name: Compilar APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema y Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Limpiar variables conflictivas de Android
        run: |
          echo "ANDROID_HOME=" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=" >> $GITHUB_ENV
          unset ANDROID_HOME
          unset ANDROID_SDK_ROOT
          unset ANDROID_NDK_ROOT
          unset ANDROID_NDK_HOME

      - name: Compilar APK con Buildozer
        run: |
          buildozer --debug android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: MiAsistente-APK
          path: bin/*.apk
          
